**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [8]:
#Code here
a = int(input("Enter number of rows (a): "))
b = int(input("Enter number of columns (b): "))

arr = np.random.rand(a, b)

print("Generated Array:")
print(arr)

average = np.mean(arr)
print("Average of the array:", round(average,2))


Generated Array:
[[0.28908888 0.57767464 0.70040434]
 [0.55452883 0.11954578 0.44734503]
 [0.93935094 0.66601615 0.27471148]]
Average of the array: 0.51


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [9]:
#Code here
def border_array(a, b):
  arr = np.ones((a, b), dtype=int)

  arr[1:-1, 1:-1] = 0

  return arr

a = int(input("Enter number of rows: "))
b = int(input("Enter number of columns: "))

result = border_array(a, b)
print("2D Array with 1 on border and 0 inside:")
print(result)

2D Array with 1 on border and 0 inside:
[[1 1]
 [1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [10]:
#Code here
vector = np.linspace(0, 1, 12)[1:-1]

print("Vector with values between 0 and 1 (excluded):")
print(vector)

Vector with values between 0 and 1 (excluded):
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [12]:
#Code here
identity_matrix = np.eye(3, 4, dtype=int)
identity_matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [13]:
#Code here
matrix = np.tile(np.arange(5), (5, 1))

print("5x5 Matrix with row values from 0 to 4:")
print(matrix)

5x5 Matrix with row values from 0 to 4:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [14]:
#code here
point = np.array([2, 3])

coords = np.random.randint(1, 101, size=(10, 2))

distances = np.linalg.norm(coords - point, axis=1)

distances_int = distances.astype(int)

print("Coordinates:\n", coords)
print("\nDistances from point [2, 3]:\n", distances_int)

Coordinates:
 [[96 63]
 [92 91]
 [16 86]
 [92  5]
 [86 96]
 [78 69]
 [16 60]
 [ 8 29]
 [42 85]
 [11 20]]

Distances from point [2, 3]:
 [111 125  84  90 125 100  58  26  91  19]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [3]:
#Code here
shape = (6, 7, 8)

# Index of the 100th element (0-based, so 99)
index = np.unravel_index(99, shape)

print("Index of the 100th element:", index)

Index of the 100th element: (np.int64(1), np.int64(5), np.int64(3))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [5]:
#Code here

input_str = input().strip()

# Convert to a NumPy array of floats
arr = np.array(input_str.split(), dtype=float)

reversed_arr = arr[::-1]
reversed_arr

array([3., 2., 1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [6]:
#Code here
arr = np.array([1, 2])

count = arr.size
print("elements_count :", count)

elements_count : 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
def softmax(arr):
  # Check if input is a 1D NumPy array
  if not isinstance(arr, np.ndarray) or arr.ndim != 1:
    raise ValueError("Input must be a 1D NumPy array")

  # Subtract max for numerical stability
  e_x = np.exp(arr - np.max(arr))
  return e_x / e_x.sum()

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [8]:
#Coder here
def vertical_stack(*arrays):
  for arr in arrays:
    if not isinstance(arr, np.ndarray):
      raise TypeError("All inputs must be NumPy arrays.")

  return np.vstack(arrays)

In [9]:
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

result = vertical_stack(a, b)
print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [10]:
#Code here
from datetime import datetime

def date_array(start, end):
  # Validate types
  if not (isinstance(start, str) and isinstance(end, str)):
    raise TypeError("Both start and end must be strings in 'YYYY-MM-DD' format.")

  try:
    # Parse strings to datetime objects
    start_date = datetime.strptime(start, '%Y-%m-%d')
    end_date = datetime.strptime(end, '%Y-%m-%d')
  except ValueError:
    raise ValueError("Date format must be 'YYYY-MM-DD'.")

  # Ensure same year
  if start_date.year != end_date.year:
    raise ValueError("Start and end dates must be in the same year.")

  # Generate dates using numpy
  num_days = (end_date - start_date).days + 1  # inclusive
  date_list = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')

  # Convert to string format
  return date_list.astype(str)

In [12]:
print(date_array(start='2020-09-15', end='2020-09-25'))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


###`Q-14:` Subtract the mean of each row from a matrix.

In [13]:
#code here
# Sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Subtract row-wise mean
result = matrix - matrix.mean(axis=1, keepdims=True)

print("Original matrix:")
print(matrix)

print("\nMatrix after subtracting row-wise mean:")
print(result)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix after subtracting row-wise mean:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [15]:
#Code here
# Sample array (2D)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original Array: ")
print(arr)

# Swap column 1 (index 0) with column 2 (index 1)
arr[:, [0, 1]] = arr[:, [1, 0]]

print("Array after swapping column 1 with column 2:")
print(arr)

Original Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after swapping column 1 with column 2:
[[2 1 3]
 [5 4 6]
 [8 7 9]]


###`Q-16:` Replace odd elements in arrays with -1.

In [16]:
#Code here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Replace odd numbers with -1
arr[arr % 2 != 0] = -1

print("Array after replacing odd numbers with -1:")
print(arr)

Array after replacing odd numbers with -1:
[-1  2 -1  4 -1  6 -1  8 -1]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [17]:
#Code here
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

# Element-wise maximum
result = np.maximum(a, b)

print("Result ->", result)

Result -> [6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [19]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 331, 4819, 8621, 3480, 9296],
       [4927,  514, 6025, 4483, 4654],
       [7436, 3832, 9344, 4544,  137],
       [4524, 2287, 9439, 7025, 8707],
       [7731, 5740, 4794,  805, 7250],
       [9527,  942, 6405, 7338, 6203],
       [ 828, 7369,  650, 1522, 2957],
       [7363, 1166, 7649, 4233, 1094]], dtype=int32)

In [22]:
#Code here
alternate_columns = arr1[:, ::2]
print("\nEvery alternate column:\n", alternate_columns)


Every alternate column:
 [[ 331 8621 9296]
 [4927 6025 4654]
 [7436 9344  137]
 [4524 9439 8707]
 [7731 4794 7250]
 [9527 6405 6203]
 [ 828  650 2957]
 [7363 7649 1094]]


In [21]:

arr1_min = arr1.min()
arr1_max = arr1.max()

arr1_normalized = (arr1 - arr1_min) / (arr1_max - arr1_min)
print("\nNormalized Array:\n", arr1_normalized)


Normalized Array:
 [[0.02066028 0.49861555 0.90351438 0.35601704 0.97539936]
 [0.51011715 0.04014909 0.62705005 0.4628328  0.48104366]
 [0.77731629 0.39350373 0.98051118 0.46932907 0.        ]
 [0.46719915 0.22896699 0.99062833 0.73354633 0.91267306]
 [0.80873269 0.59669862 0.49595314 0.07113951 0.75750799]
 [1.         0.0857295  0.66751864 0.76687966 0.64600639]
 [0.07358892 0.77018104 0.05463259 0.14749734 0.30031949]
 [0.76954207 0.10958466 0.8        0.43620873 0.10191693]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [23]:
#Code here
def nth_largest(arr, n):
  if not isinstance(arr, np.ndarray) or arr.ndim != 1:
    raise ValueError("First argument must be a 1D NumPy array.")
  if not isinstance(n, int) or n < 1 or n > len(arr):
    raise ValueError("Second argument must be an integer in the range [1, len(arr)].")

  # Use numpy's sort and indexing to get nth largest
  sorted_arr = np.sort(arr)[::-1]  # Sort in descending order
  return sorted_arr[n - 1]

In [24]:
print(nth_largest(np.array([12, 34, 40, 7, 1, 0]), 3))  # Output: 12
print(nth_largest(np.array([12, 34, 40, 7, 1, 0]), 1))  # Output: 40

12
40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
a = np.array([1, 2, 3])

# First part: Repeat each element 3 times
part1 = np.repeat(a, 3)

# Second part: Tile the array 3 times
part2 = np.tile(a, 3)

# Combine both
result = np.concatenate((part1, part2))
print("Patterned Array:\n", result)

Patterned Array:
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
