###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr = 
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [1]:
import numpy as np

In [2]:
# code here

# Step 1: Create a random 3x4 matrix with values from 0 to 100
np.random.seed(0)  # for reproducibility
arr = np.random.randint(0, 101, size=(4, 3))
print("Original array:\n", arr)

# i. Sort each row individually
sorted_rows = np.sort(arr, axis=1)
print("\n(i) np.sort (row-wise):\n", sorted_rows)

# ii. Sort based on values in 2nd column (index 1)
sorted_by_2nd_col = arr[np.argsort(arr[:, 1])]
print("\n(ii) Sorted by 2nd column:\n", sorted_by_2nd_col)

# iii. Sort rows based on max value in each row
sorted_by_row_max = arr[np.argsort(np.max(arr, axis=1))]
print("\n(iii) Sorted by row-wise max value:\n", sorted_by_row_max)

# iv. Sort all elements as a flat array and reshape back to original shape
sorted_all = np.sort(arr, axis=None).reshape(arr.shape)
print("\n(iv) Entire matrix sorted element-wise:\n", sorted_all)

Original array:
 [[44 47 64]
 [67 67  9]
 [83 21 36]
 [87 70 88]]

(i) np.sort (row-wise):
 [[44 47 64]
 [ 9 67 67]
 [21 36 83]
 [70 87 88]]

(ii) Sorted by 2nd column:
 [[83 21 36]
 [44 47 64]
 [67 67  9]
 [87 70 88]]

(iii) Sorted by row-wise max value:
 [[44 47 64]
 [67 67  9]
 [83 21 36]
 [87 70 88]]

(iv) Entire matrix sorted element-wise:
 [[ 9 21 36]
 [44 47 64]
 [67 67 70]
 [83 87 88]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [8]:
# code here
# Given data
marks = np.array([[13, 10,  9, 33],
                  [63, 46, 90, 42],
                  [39, 76, 13, 29],
                  [82,  9, 29, 78],
                  [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92])
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]

In [9]:
extra_subject = extra_subject.reshape(-1, 1)  # Make it a column
marks = np.hstack((marks, extra_subject))
print("\n(i) Marks after adding extra subject:\n", marks)



(i) Marks after adding extra subject:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]


In [19]:
new_students = np.array([rec1, rec2])  # Shape (2, 5)
marks = np.vstack((marks, new_students))
print("\n(ii) Marks after adding 2 new students:\n", marks)



(ii) Marks after adding 2 new students:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]
 [77 83 98 95 89]
 [92 71 52 61 53]]


In [20]:
total_marks = marks.sum(axis=1).reshape(-1, 1)
marks = np.hstack((marks, total_marks))
print("\n(iii) Marks with total column:\n", marks)



(iii) Marks with total column:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


In [21]:
sorted_marks = marks[np.argsort(marks[:, -1])[::-1]]  # Sort descending
top_2 = sorted_marks[:2]
print("\n(iv) Top 2 students based on total marks:\n", top_2)



(iv) Top 2 students based on total marks:
 [[ 77  83  98  95  89 442]
 [ 77  83  98  95  89 442]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [22]:
# code here
arr = np.array([[1, 2, 3, 3, 1, 1],
                [0, 9, 1, 2, 8, 8],
                [1, 2, 3, 8, 8, 8],
                [1, 2, 3, 3, 1, 1]])

In [23]:
unique_rows = np.unique(arr, axis=0)
print("Row-wise Unique:\n", unique_rows)


Row-wise Unique:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]


In [24]:
unique_cols = np.unique(arr, axis=1)
print("\nColumn-wise Unique:\n", unique_cols)



Column-wise Unique:
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [25]:
# code here
# Sample 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip along both axes
flipped = arr[::-1, ::-1]

print("Original Array:\n", arr)
print("\nFlipped Array (both axes):\n", flipped)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Array (both axes):
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6
```

In [ ]:
# code here
# Given array and value of X
arr = np.array([[1, 2, 3, 4, 5],
                [10, -3, 30, 4, 5],
                [3, 2, 5, -4, 5],
                [9, 7, 3, 6, 5]])

X = 6

# Find row indices where any element in the row is greater than X
row_indices = np.where(np.any(arr > X, axis=1))[0]

print("Row indices with element > X:", row_indices)

Row indices with element > X: [1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [14]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [27]:
# code here
# Given arrays
arr1 = np.arange(3)       # [0 1 2]
arr2 = np.arange(3, 7)    # [3 4 5 6]
arr3 = np.arange(7, 10)   # [7 8 9]

# Combine and flatten
flat_array = np.concatenate((arr1, arr2, arr3))

print("Flat 1D array:", flat_array)

Flat 1D array: [0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [28]:
# code here
# Step 1: Generate the array
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

# Step 2: Flatten the array to 1D
arr_flat = arr.flatten()

# Step 3: Find min and max
min_val = arr_flat.min()
max_val = arr_flat.max()

# Step 4: Remove first occurrence of min and max
arr_filtered = arr_flat[arr_flat != min_val]  # remove all min
arr_filtered = arr_filtered[arr_filtered != max_val]  # remove all max

# Optional: To remove only the first occurrence of each
# arr_filtered = arr_flat.tolist()
# arr_filtered.remove(min_val)
# arr_filtered.remove(max_val)
# arr_filtered = np.array(arr_filtered)

# Final Result
print("Minimum value removed:", min_val)
print("Maximum value removed:", max_val)
print("New array shape:", arr_filtered.shape)
print("Filtered array:\n", arr_filtered)

Minimum value removed: 103
Maximum value removed: 998
New array shape: (198,)
Filtered array:
 [448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
 921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
 270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [29]:
# code here

# Generate the array
np.random.seed(0)
arr = np.random.randint(100, 701, 50)

# Step 1: Clip the array to keep elements between 100 and 200
clipped_arr = np.clip(arr, 100, 200)

# Step 2: Sort the array
sorted_arr = np.sort(clipped_arr)

# Step 3: Cumulative sum
cumsum_arr = np.cumsum(sorted_arr)

# Display results
print("Original Array:\n", arr)
print("\nClipped Array (100 to 200):\n", clipped_arr)
print("\nSorted Array:\n", sorted_arr)
print("\nCumulative Sum:\n", cumsum_arr)

Original Array:
 [659 292 459 109 377 699 170 572 700 496 414 586 651 187 274 700 637 172
 215 531 548 199 277 247 523 388 365 644 643 344 251 610 559 283 128 228
 228 153 650 588 373 435 488 142 542 643 357 421 157 391]

Clipped Array (100 to 200):
 [200 200 200 109 200 200 170 200 200 200 200 200 200 187 200 200 200 172
 200 200 200 199 200 200 200 200 200 200 200 200 200 200 200 200 128 200
 200 153 200 200 200 200 200 142 200 200 200 200 157 200]

Sorted Array:
 [109 128 142 153 157 170 172 187 199 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200]

Cumulative Sum:
 [ 109  237  379  532  689  859 1031 1218 1417 1617 1817 2017 2217 2417
 2617 2817 3017 3217 3417 3617 3817 4017 4217 4417 4617 4817 5017 5217
 5417 5617 5817 6017 6217 6417 6617 6817 7017 7217 7417 7617 7817 8017
 8217 8417 8617 8817 9017 9217 9417 9617]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [30]:
# code here

# Step 1: Generate array with values in [0, 1]
np.random.seed(42)
arr = np.random.rand(100)

# Step 2: Round elements to 3 decimal places
arr = np.round(arr, 3)

# Step 3: Compare percentiles
p0 = np.percentile(arr, 0)
p100 = np.percentile(arr, 100)
min_val = arr.min()
max_val = arr.max()

# Step 4: Difference between 51st and 50th percentile
p50 = np.percentile(arr, 50)
p51 = np.percentile(arr, 51)
difference = p51 - p50

# Print results
print("Array:\n", arr)
print("\n0th Percentile:", p0, "== Min:", min_val)
print("100th Percentile:", p100, "== Max:", max_val)
print("\nDifference between 51st and 50th percentile:", round(difference, 6))


Array:
 [0.375 0.951 0.732 0.599 0.156 0.156 0.058 0.866 0.601 0.708 0.021 0.97
 0.832 0.212 0.182 0.183 0.304 0.525 0.432 0.291 0.612 0.139 0.292 0.366
 0.456 0.785 0.2   0.514 0.592 0.046 0.608 0.171 0.065 0.949 0.966 0.808
 0.305 0.098 0.684 0.44  0.122 0.495 0.034 0.909 0.259 0.663 0.312 0.52
 0.547 0.185 0.97  0.775 0.939 0.895 0.598 0.922 0.088 0.196 0.045 0.325
 0.389 0.271 0.829 0.357 0.281 0.543 0.141 0.802 0.075 0.987 0.772 0.199
 0.006 0.815 0.707 0.729 0.771 0.074 0.358 0.116 0.863 0.623 0.331 0.064
 0.311 0.325 0.73  0.638 0.887 0.472 0.12  0.713 0.761 0.561 0.771 0.494
 0.523 0.428 0.025 0.108]

0th Percentile: 0.006 == Min: 0.006
100th Percentile: 0.987 == Max: 0.987

Difference between 51st and 50th percentile: 0.01878
